// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorkForceManagerAPI.Data;

#nullable disable

namespace WorkForceManagerAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WorkForceManagerAPI.Models.Entities.Area", b =>
                {
                    b.Property<int>("AreaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AreaId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("AreaId");

                    b.ToTable("Areas", (string)null);
                });

            modelBuilder.Entity("WorkForceManagerAPI.Models.Entities.Asistencia", b =>
                {
                    b.Property<int>("AsistenciaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AsistenciaId"));

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<string>("EstadoAsistencia")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("FechaHoraEntrada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaHoraSalida")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int?>("HorarioId")
                        .HasColumnType("int");

                    b.Property<decimal?>("HorasTrabajadasReal")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("MinutosRetraso")
                        .HasColumnType("decimal(6,2)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AsistenciaId");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("HorarioId");

                    b.ToTable("Asistencia", (string)null);
                });

            modelBuilder.Entity("WorkForceManagerAPI.Models.Entities.CalculoHoras", b =>
                {
                    b.Property<int>("CalculoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CalculoId"));

                    b.Property<int?>("AsistenciaId")
                        .HasColumnType("int");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaCalculo")
                        .HasColumnType("datetime2");

                    b.Property<int>("HorarioId")
                        .HasColumnType("int");

                    b.Property<decimal>("HorasExtras")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("HorasFaltantes")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("HorasProgramadas")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("HorasTrabajadasReal")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("MinutosRetraso")
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal>("PorcentajeCumplimiento")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("CalculoId");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("HorarioId");

                    b.ToTable("CalculoHoras", (string)null);
                });

            modelBuilder.Entity("WorkForceManagerAPI.Models.Entities.Cargo", b =>
                {
                    b.Property<int>("CargoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CargoId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CargoId");

                    b.ToTable("Cargos", (string)null);
                });

            modelBuilder.Entity("WorkForceManagerAPI.Models.Entities.Empleado", b =>
                {
                    b.Property<int>("EmpleadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmpleadoId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("AreaId")
                        .HasColumnType("int");

                    b.Property<int>("CargoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("FechaIngreso")
                        .HasColumnType("date");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NumeroDocumento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("EmpleadoId");

                    b.HasIndex("AreaId");

                    b.HasIndex("CargoId");

                    b.HasIndex("NumeroDocumento")
                        .IsUnique();

                    b.ToTable("Empleados", (string)null);
                });

            modelBuilder.Entity("WorkForceManagerAPI.Models.Entities.Horario", b =>
                {
                    b.Property<int>("HorarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HorarioId"));

                    b.Property<int>("AsignadoPorUsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("datetime2");

                    b.Property<TimeOnly>("HoraFinProgramada")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("HoraInicioProgramada")
                        .HasColumnType("time");

                    b.Property<decimal>("HorasProgramadas")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoTurnoId")
                        .HasColumnType("int");

                    b.HasKey("HorarioId");

                    b.HasIndex("AsignadoPorUsuarioId");

                    b.HasIndex("TipoTurnoId");

                    b.HasIndex("EmpleadoId", "Fecha")
                        .IsUnique();

                    b.ToTable("Horarios", (string)null);
                });

            modelBuilder.Entity("WorkForceManagerAPI.Models.Entities.Rol", b =>
                {
                    b.Property<int>("RolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RolId"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RolId");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("WorkForceManagerAPI.Models.Entities.TipoTurno", b =>
                {
                    b.Property<int>("TipoTurnoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoTurnoId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<TimeOnly>("HoraFin")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("time");

                    b.Property<decimal>("HorasEsperadas")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TipoTurnoId");

                    b.ToTable("TiposTurno", (string)null);
                });

            modelBuilder.Entity("WorkForceManagerAPI.Models.Entities.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnType("datetime2");

                    b.HasKey("UsuarioId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("EmpleadoId")
                        .IsUnique();

                    b.HasIndex("RolId");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("WorkForceManagerAPI.Models.Entities.Asistencia", b =>
                {
                    b.HasOne("WorkForceManagerAPI.Models.Entities.Empleado", "Empleado")
                        .WithMany("Asistencias")
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkForceManagerAPI.Models.Entities.Horario", "Horario")
                        .WithMany("Asistencias")
                        .HasForeignKey("HorarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Empleado");

                    b.Navigation("Horario");
                });

            modelBuilder.Entity("WorkForceManagerAPI.Models.Entities.CalculoHoras", b =>
                {
                    b.HasOne("WorkForceManagerAPI.Models.Entities.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkForceManagerAPI.Models.Entities.Horario", "Horario")
                        .WithMany()
                        .HasForeignKey("HorarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empleado");

                    b.Navigation("Horario");
                });

            modelBuilder.Entity("WorkForceManagerAPI.Models.Entities.Empleado", b =>
                {
                    b.HasOne("WorkForceManagerAPI.Models.Entities.Area", "Area")
                        .WithMany("Empleados")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkForceManagerAPI.Models.Entities.Cargo", "Cargo")
                        .WithMany("Empleados")
                        .HasForeignKey("CargoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("Cargo");
                });

            modelBuilder.Entity("WorkForceManagerAPI.Models.Entities.Horario", b =>
                {
                    b.HasOne("WorkForceManagerAPI.Models.Entities.Usuario", "AsignadoPor")
                        .WithMany()
                        .HasForeignKey("AsignadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WorkForceManagerAPI.Models.Entities.Empleado", "Empleado")
                        .WithMany("Horarios")
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkForceManagerAPI.Models.Entities.TipoTurno", "TipoTurno")
                        .WithMany("Horarios")
                        .HasForeignKey("TipoTurnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AsignadoPor");

                    b.Navigation("Empleado");

                    b.Navigation("TipoTurno");
                });

            modelBuilder.Entity("WorkForceManagerAPI.Models.Entities.Usuario", b =>
                {
                    b.HasOne("WorkForceManagerAPI.Models.Entities.Empleado", "Empleado")
                        .WithOne("Usuario")
                        .HasForeignKey("WorkForceManagerAPI.Models.Entities.Usuario", "EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkForceManagerAPI.Models.Entities.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("WorkForceManagerAPI.Models.Entities.Area", b =>
                {
                    b.Navigation("Empleados");
                });

            modelBuilder.Entity("WorkForceManagerAPI.Models.Entities.Cargo", b =>
                {
                    b.Navigation("Empleados");
                });

            modelBuilder.Entity("WorkForceManagerAPI.Models.Entities.Empleado", b =>
                {
                    b.Navigation("Asistencias");

                    b.Navigation("Horarios");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("WorkForceManagerAPI.Models.Entities.Horario", b =>
                {
                    b.Navigation("Asistencias");
                });

            modelBuilder.Entity("WorkForceManagerAPI.Models.Entities.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("WorkForceManagerAPI.Models.Entities.TipoTurno", b =>
                {
                    b.Navigation("Horarios");
                });
#pragma warning restore 612, 618
        }
    }
}
